apiVersion: v1
kind: Pod
metadata:
  name: elk
  labels:
    app: elk
spec:
  containers:
    - name: elk
      image: vinodgopireddy2/elk:latest
      volumeMounts:
        - name: data
          mountPath: /var/lib/elasticsearch
  volumes:
    - name: data
      hostPath:
        path: /mnt/stateful_partition/data/elk
        type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  type: NodePort
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
    - name: kibana
      port: 5601
      targetPort: 5601
      nodePort: 30601
  selector:
    app: elk