apiVersion: v1
kind: Pod
metadata:
  name: iam
  labels:
    app: iam
spec:
  containers:
    - name: iam
      image: vinodgopireddy2/iam:latest
---
apiVersion: v1
kind: Service
metadata:
  name: iam
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: iam