#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongo
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: vinodgopireddy2/mongo:1.0
      volumeMounts:
        - name: data
          mountPath: /data/db
  volumes:
    - name: data
      hostPath:
        path: /mnt/stateful_partition/data/mongo
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: http
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
