filebeat.inputs:
- type: log
  paths:
    - /var/iam/logs/iam.log

output.elasticsearch:
  hosts: ["http://elk:9200"]
  index: "iam-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.name: "iam"
setup.template.pattern: "iam-*"